services:
  backend:
    build: ./backend
    container_name: LoginPageTEST-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: LoginPageTEST-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
